version: 2.1

orbs:
  slack: circleci/slack@4.4.4

parameters:
  terraform_apply:
    type: boolean
    default: true
  terraform_destroy:
    type: boolean
    default: false

jobs:
  slack_notify:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - slack/notify:
          custom: 'Start to Create or Update the EKS cluster via terraform by $CIRCLE_USERNAME'
          channel: circleci-notification

workflows:
  terraform_create_eks_cluster:
    when: << pipeline.parameters.terraform_apply >>
    jobs:
      - slack_notify