version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  terraform: circleci/terraform@3.0.0

parameters:
  terraform_apply:
    type: boolean
    default: false
  terraform_destroy:
    type: boolean
    default: true

jobs:
  slack_notify:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Start to Create or Update or Remove the EKS cluster via terraform by $CIRCLE_USERNAME",
                      "emoji": true
                    }
                  ]
                },
                {
                  "type": "divider"
                }
              ]
            }
          event: always
          channel: circleci-notification

  slack_approve:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - slack/notify:
          custom: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "Confirm Infra change to EKS cluster start by $CIRCLE_USERNAME."
            			}
            		},
                    {
                      "type": "divider"
                    },
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Type:*\nTerraform Apply"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Reason:*\nNew change to EKS infra."
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Specs:*\nVisionGrp EKS change to Training Account"
            				}
            			]
            		},
            		{
            			"type": "actions",
            			"elements": [
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"emoji": true,
            						"text": "Approve"
            					},
            					"style": "primary",
            					"value": "click_me_123"
            				},
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"emoji": true,
            						"text": "Deny"
            					},
            					"style": "danger",
            					"value": "click_me_123"
            				}
            			]
            		},
                    {
                      "type": "divider"
                    }
            	]
            }
          event: always
          channel: circleci-notification

  terraform_init:
    docker:
      - image: hashicorp/terraform:0.12.31
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .

  terraform_apply:
    docker:
      - image: hashicorp/terraform:0.12.31
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .

  terraform_destroy:
    docker:
      - image: hashicorp/terraform:0.12.31
    steps:
      - checkout
      - terraform/init:
          backend: true
          backend_config_file: backend.hcl
          path: .
      - terraform/plan:
          backend_config_file: backend.hcl
          path: .
      - terraform/destroy:
          path: .

workflows:
  terraform_create_eks_cluster:
    when: << pipeline.parameters.terraform_apply >>
    jobs:
      - slack_notify

      - terraform_init:
          requires:
            - slack_notify

      - slack_approve:
          requires:
            - terraform_init

      - terraform_apply:
          requires:
            - slack_approve

  terraform_remove_eks_cluster:
    when: << pipeline.parameters.terraform_destroy >>
    jobs:
      - slack_notify

      - terraform_init:
          requires:
            - slack_notify

      - slack_approve:
          requires:
            - terraform_init

      - terraform_destroy:
          requires:
            - slack_approve